### ISSUE TITLE
Exception: device not connected after renaming controller_params.py into params.py

### ISSUE THREAD

**Issue by jmller** [tum-lkn/NCSbench#2]
I'm sorry to bother you again but it's still not quite working out. After copying and renaming controller_params.py into params.py I still run into the following error:
![image](https://user-images.githubusercontent.com/59137856/76326527-0b04fe00-62e9-11ea-80da-6162e2fe55dd.png)
Is the params.py still causing this? The ev3 is properly connected with a xubuntu 18.04 LTS PC via USB and goes online. I've already checked the connection to the sensors.
Thanks in advance

**Comment by szoppi** [comment]
Hi Jmller,

This happens when the connections to the two motors are missing (cable not fully plugged) or in the wrong ports (https://github.com/ev3dev/ev3dev-lang-python/issues/257).  

Make sure that your physical connections are the same of the ones in the code:     
`motorLeft = ev3.LargeMotor('outC')`
`motorRight = ev3.LargeMotor('outB')`
