### ISSUE TITLE
BT disconnects as soon as ./robot.sh is started

### ISSUE THREAD

**Issue by jmller** [tum-lkn/NCSbench#3]
Hello!
As stated above I now try to control the robot via Bluetooth. I use a Thinkpad X201T (xubuntu 18.04.4) with built-in BT in order to connect to the ev3. As soon as I start the robot.sh via the ssh shell and type in the correct password for sudo, the terminal becomes irresponsive and the connection breaks. I have already tried to launch it several times without any luck. Every time the BT connection breaks down on me, making it impossible to close the control loop. Launching it with USB connected works fine and keeps the robot connected. Do you have any idea what could provoke this kind of behaviour when connected to BT? What type of connection with what hardware have you used while testing the NCS?

Thank you for your quick and helpful responses in the past! :) 
Greetings

**Comment by szoppi** [comment]
Hi Jmller,

The problem comes from this command in robot.sh

`rmmod legoev3_bluetooth 2>/dev/null`,

which is introduced to reduce the CPU load of the robot. You can remove this line and the connection will be maintained.

I only have one remark about your setup. By using a BT connection instead of a Wi-Fi or Ethernet, the risk is that the communication latency increases and the robot cannot be controlled over the network. In order to be controlled the robot requires 35ms round-trip delay!

Good luck!
